AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-resume-backend

  Sample SAM Template for aws-resume-backend

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  CounterFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: counter/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref CounterTable
      Architectures:
        - x86_64
      Events:
        IncrementCounter:
          Type: Api 
          Properties:
            Path: /counter
            Method: get
  CounterTable: 
    Type: AWS::Serverless::SimpleTable
    Properties: 
      TableName: counterDatabase