name: Deploy to AWS

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assume AWS deploy role
        id: assume_aws_role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::561511046884:role/GithubActionsRole
          aws-region: us-east-1  # Replace with your AWS region

      - name: Deploy to AWS
        run: |
          # Your deployment commands using assumed role credentials
          aws s3 sync ./path/to/deploy s3://your-bucket-name
          aws lambda update-function-code --function-name your-function-name --zip-file fileb://lambda.zip
          # Other deployment commands as needed
