on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build --use-container

      # - name: Run Cypress tests
      #   run: |
      #     npm install cypress --save-dev
      #     npx cypress open
      #     npx cypress run --spec "cypress/e2e/lambdaApiGateway.cy.js"
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
