name: Python AWS CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file name

      - name: Run Python tests
        run: |
          pytest  

      - name: Install Cypress
        run: |
          npm install cypress --save-dev

      - name: Run Cypress tests
        run: |
          npx cypress run  # Adjust this command as per your Cypress setup

      - name: Deploy to AWS
        run: |
          # Use AWS CLI or SDK to deploy to AWS using the provided credentials
